In [1]:
import cv2

## reading the color image

In [18]:
img = cv2.imread("wallpapers_for PC/saurav ganguly batting hd photo.jpg",1)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print("Shape of the image",img.shape,"\nSize of the image",img.size,"\nType of the image",type(img))

Shape of the image (1240, 1600, 3) 
Size of the image 5952000 
Type of the image <class 'numpy.ndarray'>


## reading the black and white image

In [4]:
black_whiteimg = cv2.imread("wallpapers_for PC/saurav ganguly batting hd photo.jpg",0)
cv2.imshow("black_whiteimg",black_whiteimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print("Shape of the image",black_whiteimg.shape,"\nSize of the image",black_whiteimg.size,"\nType of the image",type(black_whiteimg))


Shape of the image (1240, 1600) 
Size of the image 1984000 
Type of the image <class 'numpy.ndarray'>


## reading the transparent image

In [6]:
transparent_image = cv2.imread("wallpapers_for PC/saurav ganguly batting hd photo.jpg",-1)
cv2.imshow("transparent_image",transparent_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
print("Shape of the image",transparent_image.shape,"\nSize of the image",transparent_image.size,"\nType of the image",type(transparent_image))

Shape of the image (1240, 1600, 3) 
Size of the image 5952000 
Type of the image <class 'numpy.ndarray'>


In [9]:
print(img)

[[[ 46  57  41]
  [ 46  57  41]
  [ 47  58  42]
  ...
  [183 180 172]
  [182 180 172]
  [184 182 174]]

 [[ 46  57  41]
  [ 46  57  41]
  [ 47  58  42]
  ...
  [183 180 172]
  [182 180 172]
  [184 182 174]]

 [[ 46  57  41]
  [ 46  57  41]
  [ 47  58  42]
  ...
  [183 180 172]
  [181 179 171]
  [184 182 174]]

 ...

 [[ 72 180 144]
  [ 72 180 144]
  [ 71 178 145]
  ...
  [ 61 178 139]
  [ 60 177 138]
  [ 60 177 138]]

 [[ 75 180 147]
  [ 75 180 147]
  [ 75 180 147]
  ...
  [ 59 176 137]
  [ 60 177 138]
  [ 62 179 140]]

 [[ 77 182 149]
  [ 76 181 148]
  [ 77 181 148]
  ...
  [ 58 175 136]
  [ 60 177 138]
  [ 63 180 141]]]


In [16]:
print(img[2])
print("done")
print(img[2][45:400])
print("done")
print(img[257][400])

[[ 46  57  41]
 [ 46  57  41]
 [ 47  58  42]
 ...
 [183 180 172]
 [181 179 171]
 [184 182 174]]
done
[[38 52 40]
 [40 54 42]
 [41 55 44]
 ...
 [49 63 51]
 [50 64 52]
 [50 64 52]]
done
[16 26 33]


## Copy and pasting particular part the image


In [29]:
img = cv2.imread("wallpapers_for PC/saurav ganguly batting hd photo.jpg",1)
copy_data = img[500:700,600:900]
img[100:300,650:950] = copy_data
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()